### ISSUE TITLE
ようこそ画面の実装

### ISSUE THREAD

**Issue by KleinChiu** [hal-tokyo-cello/cello-game#9]
# ようこそ画面

![](https://media.discordapp.net/attachments/986158412159156274/986158479821656086/index.jpg?width=1158&height=651)

## レイアウト

- [ ] サインインボタン
- [ ] サインアップボタン

## 機能

- [ ] サインインボタンを押したら、サインイン画面に移動
- [ ] サインアップボタンを押したら、サインアップ画面に移動

**Comment by KAIN-PAC** [comment]
使わんこんなくそ画面。
